// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/base/scanner.flex

package com.codigo;
import java_cup.runtime.Symbol;

@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\3\0\1\5\1\0\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\0\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\15\1\22\1\15\1\23\1\15\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\0\1\32\1\33"+
    "\1\34\1\35\2\32\2\36\1\37\2\36\1\40\16\36"+
    "\1\41\1\42\1\43\1\0\1\44\1\0\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\36"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\36\1\64"+
    "\1\65\1\66\1\67\1\70\1\71\1\72\1\73\1\36"+
    "\1\74\1\75\1\76\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\15\1\17\3\20\1\21\1\22\20\20\1\23\1\1"+
    "\1\24\1\0\1\25\1\0\1\26\1\15\1\27\1\30"+
    "\26\20\1\31\1\32\21\20\1\0\20\20\1\33\3\20"+
    "\1\34\2\20\1\35\1\20\1\34\1\36\12\20\1\37"+
    "\2\20\1\40\1\20\1\0\1\20\1\41\4\20\1\42"+
    "\1\20\1\43\1\20\1\44\4\20\1\45\1\46\1\47"+
    "\20\20\1\0\4\20\1\50\1\51\1\52\14\20\1\53"+
    "\3\20\1\54\1\55\1\0\14\20\1\56\2\20\1\57"+
    "\1\60\1\61\1\62\1\63\4\20\1\64\1\65\1\66"+
    "\10\20\1\67\6\20\1\70\1\71\1\20";

  private static int [] zzUnpackAction() {
    int [] result = new int[242];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\77\0\176\0\275\0\374\0\77\0\77"+
    "\0\u013b\0\77\0\77\0\77\0\77\0\u017a\0\77\0\77"+
    "\0\u01b9\0\u01f8\0\u0237\0\77\0\u0276\0\u02b5\0\u02f4\0\77"+
    "\0\77\0\u0333\0\u0372\0\u03b1\0\u03f0\0\u042f\0\u046e\0\u04ad"+
    "\0\u04ec\0\u052b\0\u056a\0\u05a9\0\u05e8\0\u0627\0\u0666\0\u06a5"+
    "\0\u06e4\0\77\0\u0723\0\77\0\275\0\77\0\u0762\0\77"+
    "\0\77\0\77\0\77\0\u07a1\0\u07e0\0\u081f\0\u085e\0\u089d"+
    "\0\u08dc\0\u091b\0\u095a\0\u0999\0\u09d8\0\u0a17\0\u0a56\0\u0a95"+
    "\0\u0ad4\0\u0b13\0\u0b52\0\u0b91\0\u0bd0\0\u0c0f\0\u0c4e\0\u0c8d"+
    "\0\u0ccc\0\u0276\0\u0d0b\0\u0d4a\0\u0d89\0\u0dc8\0\u0e07\0\u0e46"+
    "\0\u0e85\0\u0ec4\0\u0f03\0\u0f42\0\u0f81\0\u0fc0\0\u0fff\0\u103e"+
    "\0\u107d\0\u10bc\0\u10fb\0\u113a\0\u1179\0\u11b8\0\u11f7\0\u1236"+
    "\0\u1275\0\u12b4\0\u12f3\0\u1332\0\u1371\0\u13b0\0\u13ef\0\u142e"+
    "\0\u146d\0\u14ac\0\u14eb\0\u152a\0\u1569\0\u0276\0\u15a8\0\u15e7"+
    "\0\u1626\0\u0276\0\u1665\0\u16a4\0\u16e3\0\u1722\0\u1761\0\u0276"+
    "\0\u17a0\0\u17df\0\u181e\0\u185d\0\u189c\0\u18db\0\u191a\0\u1959"+
    "\0\u1998\0\u19d7\0\u0276\0\u1a16\0\u1a55\0\u0276\0\u1a94\0\u1ad3"+
    "\0\u1b12\0\u0276\0\u1b51\0\u1b90\0\u1bcf\0\u1c0e\0\u0276\0\u1c4d"+
    "\0\u0276\0\u1c8c\0\u0276\0\u1ccb\0\u1d0a\0\u1d49\0\u1d88\0\u0276"+
    "\0\u0276\0\u0276\0\u1dc7\0\u1e06\0\u1e45\0\u1e84\0\u1ec3\0\u1f02"+
    "\0\u1f41\0\u1f80\0\u1fbf\0\u1ffe\0\u203d\0\u207c\0\u20bb\0\u20fa"+
    "\0\u2139\0\u2178\0\u21b7\0\u21f6\0\u2235\0\u2274\0\u22b3\0\u0276"+
    "\0\u0276\0\u0276\0\u22f2\0\u2331\0\u2370\0\u23af\0\u23ee\0\u242d"+
    "\0\u246c\0\u24ab\0\u24ea\0\u2529\0\u2568\0\u25a7\0\u0276\0\u25e6"+
    "\0\u2625\0\u2664\0\u0276\0\u0276\0\u26a3\0\u26e2\0\u2721\0\u2760"+
    "\0\u279f\0\u27de\0\u281d\0\u285c\0\u289b\0\u28da\0\u2919\0\u2958"+
    "\0\u2997\0\u0276\0\u29d6\0\u2a15\0\u0276\0\u0276\0\u0276\0\u0276"+
    "\0\u0276\0\u2a54\0\u2a93\0\u2ad2\0\u2b11\0\u0276\0\u0276\0\u0276"+
    "\0\u2b50\0\u2b8f\0\u2bce\0\u2c0d\0\u2c4c\0\u2c8b\0\u2cca\0\u2d09"+
    "\0\u0276\0\u2d48\0\u2d87\0\u2dc6\0\u2e05\0\u2e44\0\u2e83\0\u0276"+
    "\0\u0276\0\u2ec2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[242];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\7\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\4\25\1\27\1\30"+
    "\1\2\1\31\1\32\1\25\1\33\1\34\1\35\1\36"+
    "\1\37\2\25\1\40\1\25\1\41\1\25\1\42\1\25"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\2\25"+
    "\1\52\1\53\1\54\101\0\1\3\74\0\4\55\1\56"+
    "\35\55\1\57\34\55\5\0\1\60\121\0\1\61\63\0"+
    "\7\16\102\0\2\61\75\0\1\61\1\62\75\0\1\61"+
    "\1\63\63\0\7\25\6\0\7\25\3\0\30\25\20\0"+
    "\7\25\6\0\7\25\3\0\11\25\1\64\16\25\20\0"+
    "\7\25\6\0\7\25\3\0\11\25\1\65\16\25\20\0"+
    "\7\25\6\0\1\25\1\66\1\67\1\70\1\25\1\71"+
    "\1\25\3\0\30\25\20\0\7\25\6\0\7\25\3\0"+
    "\16\25\1\72\1\25\1\73\6\25\1\74\20\0\7\25"+
    "\6\0\7\25\3\0\1\25\1\75\6\25\1\76\2\25"+
    "\1\77\14\25\20\0\7\25\6\0\7\25\3\0\5\25"+
    "\1\100\10\25\1\101\11\25\20\0\7\25\6\0\7\25"+
    "\3\0\13\25\1\102\1\25\1\103\12\25\20\0\5\25"+
    "\1\104\1\25\6\0\7\25\3\0\11\25\1\105\1\25"+
    "\1\106\2\25\1\107\4\25\1\110\4\25\20\0\3\25"+
    "\1\111\3\25\6\0\7\25\3\0\6\25\1\112\6\25"+
    "\1\113\12\25\20\0\7\25\6\0\7\25\3\0\5\25"+
    "\1\114\10\25\1\115\11\25\20\0\7\25\6\0\7\25"+
    "\3\0\1\25\1\116\26\25\20\0\7\25\6\0\7\25"+
    "\3\0\20\25\1\117\2\25\1\120\4\25\20\0\7\25"+
    "\6\0\7\25\3\0\5\25\1\121\22\25\20\0\7\25"+
    "\6\0\7\25\3\0\2\25\1\122\1\123\4\25\1\124"+
    "\11\25\1\125\2\25\1\126\2\25\20\0\7\25\6\0"+
    "\7\25\3\0\20\25\1\127\7\25\20\0\3\25\1\111"+
    "\3\25\6\0\7\25\3\0\11\25\1\130\1\25\1\131"+
    "\5\25\1\132\6\25\20\0\7\25\6\0\7\25\3\0"+
    "\1\25\1\133\26\25\20\0\7\25\6\0\7\25\3\0"+
    "\10\25\1\134\17\25\100\0\1\60\5\0\1\55\7\0"+
    "\1\55\25\0\1\55\3\0\1\55\3\0\1\55\6\0"+
    "\1\55\2\0\1\55\1\0\1\55\1\135\24\0\7\25"+
    "\6\0\7\25\3\0\7\25\1\136\20\25\20\0\7\25"+
    "\6\0\7\25\3\0\21\25\1\137\6\25\20\0\7\25"+
    "\6\0\7\25\3\0\11\25\1\140\16\25\20\0\7\25"+
    "\6\0\7\25\3\0\16\25\1\141\11\25\20\0\7\25"+
    "\6\0\7\25\3\0\5\25\1\142\22\25\20\0\7\25"+
    "\6\0\7\25\3\0\14\25\1\143\13\25\20\0\7\25"+
    "\6\0\7\25\3\0\16\25\1\144\11\25\20\0\7\25"+
    "\6\0\7\25\3\0\5\25\1\145\22\25\20\0\7\25"+
    "\6\0\7\25\3\0\22\25\1\146\5\25\20\0\7\25"+
    "\6\0\7\25\3\0\21\25\1\147\1\150\5\25\20\0"+
    "\7\25\6\0\7\25\3\0\1\25\1\151\26\25\20\0"+
    "\7\25\6\0\7\25\3\0\1\25\1\152\26\25\20\0"+
    "\7\25\6\0\7\25\3\0\3\25\1\153\2\25\1\154"+
    "\21\25\20\0\7\25\6\0\7\25\3\0\23\25\1\155"+
    "\1\25\1\156\2\25\20\0\7\25\6\0\7\25\3\0"+
    "\11\25\1\157\7\25\1\160\6\25\20\0\7\25\6\0"+
    "\7\25\3\0\23\25\1\161\4\25\20\0\4\25\1\162"+
    "\2\25\6\0\7\25\3\0\30\25\20\0\7\25\6\0"+
    "\7\25\3\0\15\25\1\163\12\25\20\0\7\25\6\0"+
    "\7\25\3\0\16\25\1\164\11\25\20\0\7\25\6\0"+
    "\7\25\3\0\20\25\1\165\7\25\20\0\7\25\6\0"+
    "\7\25\3\0\15\25\1\166\12\25\20\0\2\25\1\162"+
    "\4\25\6\0\7\25\3\0\30\25\20\0\7\25\6\0"+
    "\7\25\3\0\22\25\1\167\5\25\20\0\7\25\6\0"+
    "\7\25\3\0\22\25\1\170\5\25\20\0\7\25\6\0"+
    "\7\25\3\0\15\25\1\171\12\25\20\0\7\25\6\0"+
    "\7\25\3\0\14\25\1\172\13\25\20\0\7\25\6\0"+
    "\7\25\3\0\11\25\1\173\4\25\1\174\11\25\20\0"+
    "\7\25\6\0\7\25\3\0\2\25\1\175\25\25\20\0"+
    "\7\25\6\0\7\25\3\0\22\25\1\176\5\25\20\0"+
    "\7\25\6\0\7\25\3\0\27\25\1\74\20\0\7\25"+
    "\6\0\7\25\3\0\1\25\1\177\26\25\20\0\7\25"+
    "\6\0\7\25\3\0\16\25\1\200\11\25\20\0\7\25"+
    "\6\0\7\25\3\0\20\25\1\201\7\25\20\0\7\25"+
    "\6\0\7\25\3\0\11\25\1\202\16\25\20\0\7\25"+
    "\6\0\7\25\3\0\27\25\1\203\20\0\7\25\6\0"+
    "\7\25\3\0\15\25\1\204\12\25\20\0\7\25\6\0"+
    "\7\25\3\0\16\25\1\115\11\25\20\0\7\25\6\0"+
    "\7\25\3\0\10\25\1\124\1\205\16\25\20\0\7\25"+
    "\6\0\7\25\3\0\20\25\1\206\7\25\20\0\7\25"+
    "\6\0\7\25\3\0\11\25\1\207\16\25\20\0\7\210"+
    "\6\0\4\210\7\0\6\210\41\0\7\25\6\0\5\25"+
    "\1\211\1\25\3\0\30\25\20\0\7\25\6\0\7\25"+
    "\3\0\22\25\1\212\5\25\20\0\7\25\6\0\7\25"+
    "\3\0\22\25\1\213\5\25\20\0\7\25\6\0\7\25"+
    "\3\0\14\25\1\214\13\25\20\0\7\25\6\0\7\25"+
    "\3\0\3\25\1\215\24\25\20\0\7\25\6\0\7\25"+
    "\3\0\1\25\1\216\26\25\20\0\7\25\6\0\7\25"+
    "\3\0\13\25\1\217\14\25\20\0\7\25\6\0\7\25"+
    "\3\0\1\25\1\220\26\25\20\0\7\25\6\0\7\25"+
    "\3\0\5\25\1\162\22\25\20\0\7\25\6\0\7\25"+
    "\3\0\5\25\1\221\22\25\20\0\7\25\6\0\7\25"+
    "\3\0\3\25\1\222\24\25\20\0\7\25\6\0\7\25"+
    "\3\0\20\25\1\223\7\25\20\0\7\25\6\0\7\25"+
    "\3\0\21\25\1\224\6\25\20\0\7\25\6\0\7\25"+
    "\3\0\11\25\1\225\16\25\20\0\7\25\6\0\7\25"+
    "\3\0\1\25\1\226\26\25\20\0\7\25\6\0\7\25"+
    "\3\0\2\25\1\227\25\25\20\0\7\25\6\0\7\25"+
    "\3\0\6\25\1\230\21\25\20\0\7\25\6\0\7\25"+
    "\3\0\5\25\1\231\22\25\20\0\7\25\6\0\7\25"+
    "\3\0\14\25\1\232\13\25\20\0\7\25\6\0\7\25"+
    "\3\0\1\25\1\233\26\25\20\0\7\25\6\0\7\25"+
    "\3\0\1\25\1\204\26\25\20\0\7\25\6\0\7\25"+
    "\3\0\5\25\1\234\22\25\20\0\7\25\6\0\7\25"+
    "\3\0\3\25\1\235\24\25\20\0\7\25\6\0\7\25"+
    "\3\0\5\25\1\236\22\25\20\0\7\25\6\0\7\25"+
    "\3\0\7\25\1\162\20\25\20\0\7\25\6\0\7\25"+
    "\3\0\5\25\1\237\22\25\20\0\7\25\6\0\7\25"+
    "\3\0\15\25\1\240\6\25\1\241\3\25\20\0\7\25"+
    "\6\0\7\25\3\0\22\25\1\242\5\25\20\0\7\25"+
    "\6\0\7\25\3\0\13\25\1\243\14\25\20\0\7\25"+
    "\6\0\7\25\3\0\23\25\1\244\4\25\20\0\7\25"+
    "\6\0\7\25\3\0\15\25\1\245\12\25\20\0\7\25"+
    "\6\0\7\25\3\0\20\25\1\204\7\25\20\0\7\25"+
    "\6\0\7\25\3\0\11\25\1\246\11\25\1\247\4\25"+
    "\20\0\7\25\6\0\7\25\3\0\22\25\1\250\5\25"+
    "\20\0\7\25\6\0\7\25\3\0\22\25\1\162\5\25"+
    "\20\0\7\25\6\0\7\25\3\0\15\25\1\251\12\25"+
    "\20\0\7\25\6\0\7\25\3\0\13\25\1\252\14\25"+
    "\20\0\7\253\6\0\4\253\7\0\6\253\41\0\7\25"+
    "\6\0\7\25\3\0\15\25\1\254\12\25\20\0\7\25"+
    "\6\0\5\25\1\130\1\25\3\0\30\25\20\0\7\25"+
    "\6\0\7\25\3\0\17\25\1\255\10\25\20\0\7\25"+
    "\6\0\7\25\3\0\11\25\1\256\16\25\20\0\7\25"+
    "\6\0\7\25\3\0\7\25\1\257\20\25\20\0\7\25"+
    "\6\0\7\25\3\0\12\25\1\260\15\25\20\0\7\25"+
    "\6\0\7\25\3\0\10\25\1\261\17\25\20\0\7\25"+
    "\6\0\7\25\3\0\21\25\1\262\6\25\20\0\7\25"+
    "\6\0\7\25\3\0\14\25\1\263\13\25\20\0\7\25"+
    "\6\0\7\25\3\0\23\25\1\264\4\25\20\0\7\25"+
    "\6\0\7\25\3\0\13\25\1\146\14\25\20\0\7\25"+
    "\6\0\7\25\3\0\13\25\1\265\14\25\20\0\7\25"+
    "\6\0\7\25\3\0\1\25\1\266\26\25\20\0\7\25"+
    "\6\0\7\25\3\0\22\25\1\267\5\25\20\0\7\25"+
    "\6\0\7\25\3\0\20\25\1\270\7\25\20\0\7\25"+
    "\6\0\7\25\3\0\21\25\1\271\6\25\20\0\7\25"+
    "\6\0\7\25\3\0\22\25\1\272\5\25\20\0\7\25"+
    "\6\0\7\25\3\0\1\25\1\273\26\25\20\0\7\25"+
    "\6\0\7\25\3\0\5\25\1\274\22\25\20\0\7\25"+
    "\6\0\7\25\3\0\11\25\1\275\16\25\20\0\7\25"+
    "\6\0\7\25\3\0\20\25\1\276\7\25\20\0\7\25"+
    "\6\0\7\25\3\0\11\25\1\277\16\25\20\0\7\25"+
    "\6\0\7\25\3\0\15\25\1\300\12\25\20\0\7\25"+
    "\6\0\7\25\3\0\3\25\1\301\24\25\20\0\7\25"+
    "\6\0\7\25\3\0\3\25\1\302\24\25\20\0\7\25"+
    "\6\0\7\25\3\0\7\25\1\303\20\25\20\0\7\25"+
    "\6\0\7\25\3\0\5\25\1\304\22\25\20\0\7\305"+
    "\6\0\4\305\7\0\6\305\41\0\7\25\6\0\7\25"+
    "\3\0\22\25\1\306\5\25\20\0\7\25\6\0\7\25"+
    "\3\0\13\25\1\307\14\25\20\0\7\25\6\0\7\25"+
    "\3\0\14\25\1\310\13\25\20\0\7\25\6\0\7\25"+
    "\3\0\11\25\1\311\16\25\20\0\7\25\6\0\7\25"+
    "\3\0\1\25\1\312\26\25\20\0\7\25\6\0\7\25"+
    "\3\0\13\25\1\313\14\25\20\0\7\25\6\0\7\25"+
    "\3\0\13\25\1\314\14\25\20\0\7\25\6\0\7\25"+
    "\3\0\3\25\1\315\24\25\20\0\7\25\6\0\7\25"+
    "\3\0\11\25\1\316\16\25\20\0\7\25\6\0\7\25"+
    "\3\0\6\25\1\317\6\25\1\320\12\25\20\0\7\25"+
    "\6\0\7\25\3\0\17\25\1\321\10\25\20\0\7\25"+
    "\6\0\7\25\3\0\16\25\1\322\11\25\20\0\7\25"+
    "\6\0\7\25\3\0\22\25\1\323\5\25\20\0\7\25"+
    "\6\0\7\25\3\0\3\25\1\324\24\25\20\0\7\25"+
    "\6\0\7\25\3\0\3\25\1\325\24\25\20\0\7\25"+
    "\6\0\7\25\3\0\15\25\1\326\12\25\20\0\7\25"+
    "\6\0\7\25\3\0\7\25\1\327\20\25\20\0\7\25"+
    "\6\0\7\25\3\0\22\25\1\330\5\25\20\0\7\25"+
    "\6\0\7\25\3\0\10\25\1\331\17\25\20\0\7\55"+
    "\6\0\4\55\7\0\6\55\41\0\7\25\6\0\7\25"+
    "\3\0\5\25\1\332\22\25\20\0\7\25\6\0\7\25"+
    "\3\0\5\25\1\333\22\25\20\0\7\25\6\0\7\25"+
    "\3\0\1\25\1\334\26\25\20\0\7\25\6\0\7\25"+
    "\3\0\15\25\1\335\12\25\20\0\7\25\6\0\7\25"+
    "\3\0\13\25\1\162\14\25\20\0\7\25\6\0\7\25"+
    "\3\0\22\25\1\336\5\25\20\0\7\25\6\0\7\25"+
    "\3\0\27\25\1\337\20\0\7\25\6\0\7\25\3\0"+
    "\10\25\1\340\17\25\20\0\7\25\6\0\7\25\3\0"+
    "\16\25\1\341\11\25\20\0\7\25\6\0\7\25\3\0"+
    "\1\25\1\342\26\25\20\0\7\25\6\0\7\25\3\0"+
    "\1\25\1\343\26\25\20\0\7\25\6\0\7\25\3\0"+
    "\1\25\1\344\26\25\20\0\7\25\6\0\7\25\3\0"+
    "\5\25\1\325\22\25\20\0\7\25\6\0\7\25\3\0"+
    "\22\25\1\345\5\25\20\0\7\25\6\0\7\25\3\0"+
    "\7\25\1\346\20\25\20\0\7\25\6\0\7\25\3\0"+
    "\26\25\1\162\1\25\20\0\7\25\6\0\7\25\3\0"+
    "\13\25\1\347\14\25\20\0\7\25\6\0\7\25\3\0"+
    "\1\25\1\350\26\25\20\0\7\25\6\0\7\25\3\0"+
    "\15\25\1\351\12\25\20\0\7\25\6\0\7\25\3\0"+
    "\3\25\1\352\24\25\20\0\7\25\6\0\7\25\3\0"+
    "\13\25\1\325\14\25\20\0\7\25\6\0\7\25\3\0"+
    "\3\25\1\353\24\25\20\0\7\25\6\0\7\25\3\0"+
    "\5\25\1\354\22\25\20\0\7\25\6\0\7\25\3\0"+
    "\5\25\1\355\22\25\20\0\1\25\1\356\1\25\1\111"+
    "\1\25\1\104\1\25\6\0\7\25\3\0\30\25\20\0"+
    "\7\25\6\0\7\25\3\0\20\25\1\357\7\25\20\0"+
    "\7\25\6\0\7\25\3\0\5\25\1\360\22\25\20\0"+
    "\7\25\6\0\7\25\3\0\5\25\1\361\22\25\20\0"+
    "\7\25\6\0\7\25\3\0\4\25\1\325\23\25\20\0"+
    "\7\25\6\0\7\25\3\0\20\25\1\162\7\25\20\0"+
    "\2\25\1\362\4\25\6\0\7\25\3\0\30\25\20\0"+
    "\7\25\6\0\7\25\3\0\27\25\1\162\20\0\6\25"+
    "\1\162\6\0\7\25\3\0\30\25\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[12033];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\2\11\1\1\4\11\1\1\2\11"+
    "\3\1\1\11\3\1\2\11\20\1\1\11\1\1\1\11"+
    "\1\0\1\11\1\0\4\11\51\1\1\0\52\1\1\0"+
    "\42\1\1\0\31\1\1\0\55\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[242];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private java_cup.runtime.Symbol symbol(int type) {
        return new java_cup.runtime.Symbol(type, yyline, yycolumn);
    }
    private java_cup.runtime.Symbol symbol(int type, Object value) {
        return new java_cup.runtime.Symbol(type, yyline, yycolumn, value);
        }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(sym.ERRORL, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 58: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 59: break;
          case 3:
            { return new Symbol(sym.PARENTESISABIERTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 60: break;
          case 4:
            { return new Symbol(sym.PARENTESISCERRADO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 61: break;
          case 5:
            { return new Symbol(sym.MULTI, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 62: break;
          case 6:
            { return new Symbol(sym.MAS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 63: break;
          case 7:
            { return new Symbol(sym.COMA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 64: break;
          case 8:
            { return new Symbol(sym.MENOS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 65: break;
          case 9:
            { return new Symbol(sym.DIV, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 66: break;
          case 10:
            { return new Symbol(sym.NUMERICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 67: break;
          case 11:
            { return new Symbol(sym.PUNTODOBLE, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 68: break;
          case 12:
            { return new Symbol(sym.PUNTOCOMA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 69: break;
          case 13:
            { return new Symbol(sym.OPERADORRELACIONAL, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 70: break;
          case 14:
            { return new Symbol(sym.OPERADORASIGNAMIENTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 71: break;
          case 15:
            { return new Symbol(sym.OPERADORTERNARIO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 72: break;
          case 16:
            { return new Symbol(sym.ID, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 73: break;
          case 17:
            { return new Symbol(sym.CORCHETEABIERTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 74: break;
          case 18:
            { return new Symbol(sym.CORCHETECERRADO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 75: break;
          case 19:
            { return new Symbol(sym.LLAVEABIERTA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 76: break;
          case 20:
            { return new Symbol(sym.LLAVECERRADA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 77: break;
          case 21:
            { return new Symbol(sym.LITERAL, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 78: break;
          case 22:
            { return new Symbol(sym.OPERADORCONLOGICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 79: break;
          case 23:
            { return new Symbol(sym.OPERADORRESULTADO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 80: break;
          case 24:
            { return new Symbol(sym.OPERADORDESPLAZAMIENTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 81: break;
          case 25:
            { return new Symbol(sym.SI, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 82: break;
          case 26:
            { return new Symbol(sym.PARAMETROENTRADA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 83: break;
          case 27:
            { return new Symbol(sym.HACER, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 84: break;
          case 28:
            { return new Symbol(sym.TIPONUMERICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 85: break;
          case 29:
            { return new Symbol(sym.POR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 86: break;
          case 30:
            { return new Symbol(sym.DEC, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 87: break;
          case 31:
            { return new Symbol(sym.INTENTAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 88: break;
          case 32:
            { return new Symbol(sym.TIPOINFERIDO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 89: break;
          case 33:
            { return new Symbol(sym.LISTA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 90: break;
          case 34:
            { return new Symbol(sym.TIPOLOGICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 91: break;
          case 35:
            { return new Symbol(sym.CASO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 92: break;
          case 36:
            { return new Symbol(sym.TIPOCARACTER, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 93: break;
          case 37:
            { return new Symbol(sym.SINOHACER, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 94: break;
          case 38:
            { return new Symbol(sym.SINO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 95: break;
          case 39:
            { return new Symbol(sym.AGRUPACIONENUMERATOR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 96: break;
          case 40:
            { return new Symbol(sym.PARAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 97: break;
          case 41:
            { return new Symbol(sym.ATRAPAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 98: break;
          case 42:
            { return new Symbol(sym.AGRUPACIONSECUNDARIA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 99: break;
          case 43:
            { return new Symbol(sym.ESCANEAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 100: break;
          case 44:
            { return new Symbol(sym.GESTIONRECURSOS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 101: break;
          case 45:
            { return new Symbol(sym.MIENTRAS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 102: break;
          case 46:
            { return new Symbol(sym.IMPRIMIR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 103: break;
          case 47:
            { return new Symbol(sym.MODIFICADORACCESO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 104: break;
          case 48:
            { return new Symbol(sym.RETORNAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 105: break;
          case 49:
            { return new Symbol(sym.TIPOCADENA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 106: break;
          case 50:
            { return new Symbol(sym.AGRUPACIONESTRUCTURA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 107: break;
          case 51:
            { return new Symbol(sym.SELECTOR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 108: break;
          case 52:
            { return new Symbol(sym.DEFECTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 109: break;
          case 53:
            { return new Symbol(sym.TERMINAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 110: break;
          case 54:
            { return new Symbol(sym.PORCADA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 111: break;
          case 55:
            { return new Symbol(sym.DECLARACIONFUNCION, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 112: break;
          case 56:
            { return new Symbol(sym.AGRUPACIONINTERFAZ, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 113: break;
          case 57:
            { return new Symbol(sym.AGRUPACIONPRINCIPAL, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
