// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/base/scanner.flex

package com.codigo;
import java_cup.runtime.Symbol;

@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\3\0\1\5\1\0\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\16\1\23\1\16\1\24\1\16\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\0\1\33\1\34"+
    "\1\35\1\36\2\33\2\37\1\40\2\37\1\41\16\37"+
    "\1\42\1\43\1\44\1\0\1\45\1\0\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\37"+
    "\1\57\1\60\1\61\1\62\1\63\1\64\1\37\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\73\1\74\1\37"+
    "\1\75\1\76\1\77\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\16\1\20\3\21\1\22\1\23\20\21\1\24"+
    "\1\1\1\25\1\0\1\26\1\0\1\27\1\16\1\30"+
    "\1\31\26\21\1\32\1\33\21\21\1\0\20\21\1\34"+
    "\3\21\1\35\2\21\1\36\1\21\1\35\1\37\12\21"+
    "\1\40\2\21\1\41\1\21\1\0\1\21\1\42\4\21"+
    "\1\43\1\21\1\44\1\21\1\45\4\21\1\46\1\47"+
    "\1\50\20\21\1\0\4\21\1\51\1\52\1\53\14\21"+
    "\1\54\3\21\1\55\1\56\1\0\14\21\1\57\2\21"+
    "\1\60\1\61\1\62\1\63\1\64\4\21\1\65\1\66"+
    "\1\67\10\21\1\70\6\21\1\71\1\72\1\21";

  private static int [] zzUnpackAction() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\100\0\200\0\300\0\u0100\0\100\0\100"+
    "\0\u0140\0\100\0\100\0\100\0\100\0\100\0\u0180\0\100"+
    "\0\100\0\u01c0\0\u0200\0\u0240\0\100\0\u0280\0\u02c0\0\u0300"+
    "\0\100\0\100\0\u0340\0\u0380\0\u03c0\0\u0400\0\u0440\0\u0480"+
    "\0\u04c0\0\u0500\0\u0540\0\u0580\0\u05c0\0\u0600\0\u0640\0\u0680"+
    "\0\u06c0\0\u0700\0\100\0\u0740\0\100\0\300\0\100\0\u0780"+
    "\0\100\0\100\0\100\0\100\0\u07c0\0\u0800\0\u0840\0\u0880"+
    "\0\u08c0\0\u0900\0\u0940\0\u0980\0\u09c0\0\u0a00\0\u0a40\0\u0a80"+
    "\0\u0ac0\0\u0b00\0\u0b40\0\u0b80\0\u0bc0\0\u0c00\0\u0c40\0\u0c80"+
    "\0\u0cc0\0\u0d00\0\u0280\0\u0d40\0\u0d80\0\u0dc0\0\u0e00\0\u0e40"+
    "\0\u0e80\0\u0ec0\0\u0f00\0\u0f40\0\u0f80\0\u0fc0\0\u1000\0\u1040"+
    "\0\u1080\0\u10c0\0\u1100\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240"+
    "\0\u1280\0\u12c0\0\u1300\0\u1340\0\u1380\0\u13c0\0\u1400\0\u1440"+
    "\0\u1480\0\u14c0\0\u1500\0\u1540\0\u1580\0\u15c0\0\u0280\0\u1600"+
    "\0\u1640\0\u1680\0\u0280\0\u16c0\0\u1700\0\u1740\0\u1780\0\u17c0"+
    "\0\u0280\0\u1800\0\u1840\0\u1880\0\u18c0\0\u1900\0\u1940\0\u1980"+
    "\0\u19c0\0\u1a00\0\u1a40\0\u0280\0\u1a80\0\u1ac0\0\u0280\0\u1b00"+
    "\0\u1b40\0\u1b80\0\u0280\0\u1bc0\0\u1c00\0\u1c40\0\u1c80\0\u0280"+
    "\0\u1cc0\0\u0280\0\u1d00\0\u0280\0\u1d40\0\u1d80\0\u1dc0\0\u1e00"+
    "\0\u0280\0\u0280\0\u0280\0\u1e40\0\u1e80\0\u1ec0\0\u1f00\0\u1f40"+
    "\0\u1f80\0\u1fc0\0\u2000\0\u2040\0\u2080\0\u20c0\0\u2100\0\u2140"+
    "\0\u2180\0\u21c0\0\u2200\0\u2240\0\u2280\0\u22c0\0\u2300\0\u2340"+
    "\0\u0280\0\u0280\0\u0280\0\u2380\0\u23c0\0\u2400\0\u2440\0\u2480"+
    "\0\u24c0\0\u2500\0\u2540\0\u2580\0\u25c0\0\u2600\0\u2640\0\u0280"+
    "\0\u2680\0\u26c0\0\u2700\0\u0280\0\u0280\0\u2740\0\u2780\0\u27c0"+
    "\0\u2800\0\u2840\0\u2880\0\u28c0\0\u2900\0\u2940\0\u2980\0\u29c0"+
    "\0\u2a00\0\u2a40\0\u0280\0\u2a80\0\u2ac0\0\u0280\0\u0280\0\u0280"+
    "\0\u0280\0\u0280\0\u2b00\0\u2b40\0\u2b80\0\u2bc0\0\u0280\0\u0280"+
    "\0\u0280\0\u2c00\0\u2c40\0\u2c80\0\u2cc0\0\u2d00\0\u2d40\0\u2d80"+
    "\0\u2dc0\0\u0280\0\u2e00\0\u2e40\0\u2e80\0\u2ec0\0\u2f00\0\u2f40"+
    "\0\u0280\0\u0280\0\u2f80";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\7\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\4\26\1\30"+
    "\1\31\1\2\1\32\1\33\1\26\1\34\1\35\1\36"+
    "\1\37\1\40\2\26\1\41\1\26\1\42\1\26\1\43"+
    "\1\26\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\2\26\1\53\1\54\1\55\102\0\1\3\75\0\4\56"+
    "\1\57\36\56\1\60\34\56\5\0\1\61\123\0\1\62"+
    "\64\0\7\17\103\0\2\62\76\0\1\62\1\63\76\0"+
    "\1\62\1\64\64\0\7\26\6\0\7\26\3\0\30\26"+
    "\21\0\7\26\6\0\7\26\3\0\11\26\1\65\16\26"+
    "\21\0\7\26\6\0\7\26\3\0\11\26\1\66\16\26"+
    "\21\0\7\26\6\0\1\26\1\67\1\70\1\71\1\26"+
    "\1\72\1\26\3\0\30\26\21\0\7\26\6\0\7\26"+
    "\3\0\16\26\1\73\1\26\1\74\6\26\1\75\21\0"+
    "\7\26\6\0\7\26\3\0\1\26\1\76\6\26\1\77"+
    "\2\26\1\100\14\26\21\0\7\26\6\0\7\26\3\0"+
    "\5\26\1\101\10\26\1\102\11\26\21\0\7\26\6\0"+
    "\7\26\3\0\13\26\1\103\1\26\1\104\12\26\21\0"+
    "\5\26\1\105\1\26\6\0\7\26\3\0\11\26\1\106"+
    "\1\26\1\107\2\26\1\110\4\26\1\111\4\26\21\0"+
    "\3\26\1\112\3\26\6\0\7\26\3\0\6\26\1\113"+
    "\6\26\1\114\12\26\21\0\7\26\6\0\7\26\3\0"+
    "\5\26\1\115\10\26\1\116\11\26\21\0\7\26\6\0"+
    "\7\26\3\0\1\26\1\117\26\26\21\0\7\26\6\0"+
    "\7\26\3\0\20\26\1\120\2\26\1\121\4\26\21\0"+
    "\7\26\6\0\7\26\3\0\5\26\1\122\22\26\21\0"+
    "\7\26\6\0\7\26\3\0\2\26\1\123\1\124\4\26"+
    "\1\125\11\26\1\126\2\26\1\127\2\26\21\0\7\26"+
    "\6\0\7\26\3\0\20\26\1\130\7\26\21\0\3\26"+
    "\1\112\3\26\6\0\7\26\3\0\11\26\1\131\1\26"+
    "\1\132\5\26\1\133\6\26\21\0\7\26\6\0\7\26"+
    "\3\0\1\26\1\134\26\26\21\0\7\26\6\0\7\26"+
    "\3\0\10\26\1\135\17\26\101\0\1\61\5\0\1\56"+
    "\10\0\1\56\25\0\1\56\3\0\1\56\3\0\1\56"+
    "\6\0\1\56\2\0\1\56\1\0\1\56\1\136\25\0"+
    "\7\26\6\0\7\26\3\0\7\26\1\137\20\26\21\0"+
    "\7\26\6\0\7\26\3\0\21\26\1\140\6\26\21\0"+
    "\7\26\6\0\7\26\3\0\11\26\1\141\16\26\21\0"+
    "\7\26\6\0\7\26\3\0\16\26\1\142\11\26\21\0"+
    "\7\26\6\0\7\26\3\0\5\26\1\143\22\26\21\0"+
    "\7\26\6\0\7\26\3\0\14\26\1\144\13\26\21\0"+
    "\7\26\6\0\7\26\3\0\16\26\1\145\11\26\21\0"+
    "\7\26\6\0\7\26\3\0\5\26\1\146\22\26\21\0"+
    "\7\26\6\0\7\26\3\0\22\26\1\147\5\26\21\0"+
    "\7\26\6\0\7\26\3\0\21\26\1\150\1\151\5\26"+
    "\21\0\7\26\6\0\7\26\3\0\1\26\1\152\26\26"+
    "\21\0\7\26\6\0\7\26\3\0\1\26\1\153\26\26"+
    "\21\0\7\26\6\0\7\26\3\0\3\26\1\154\2\26"+
    "\1\155\21\26\21\0\7\26\6\0\7\26\3\0\23\26"+
    "\1\156\1\26\1\157\2\26\21\0\7\26\6\0\7\26"+
    "\3\0\11\26\1\160\7\26\1\161\6\26\21\0\7\26"+
    "\6\0\7\26\3\0\23\26\1\162\4\26\21\0\4\26"+
    "\1\163\2\26\6\0\7\26\3\0\30\26\21\0\7\26"+
    "\6\0\7\26\3\0\15\26\1\164\12\26\21\0\7\26"+
    "\6\0\7\26\3\0\16\26\1\165\11\26\21\0\7\26"+
    "\6\0\7\26\3\0\20\26\1\166\7\26\21\0\7\26"+
    "\6\0\7\26\3\0\15\26\1\167\12\26\21\0\2\26"+
    "\1\163\4\26\6\0\7\26\3\0\30\26\21\0\7\26"+
    "\6\0\7\26\3\0\22\26\1\170\5\26\21\0\7\26"+
    "\6\0\7\26\3\0\22\26\1\171\5\26\21\0\7\26"+
    "\6\0\7\26\3\0\15\26\1\172\12\26\21\0\7\26"+
    "\6\0\7\26\3\0\14\26\1\173\13\26\21\0\7\26"+
    "\6\0\7\26\3\0\11\26\1\174\4\26\1\175\11\26"+
    "\21\0\7\26\6\0\7\26\3\0\2\26\1\176\25\26"+
    "\21\0\7\26\6\0\7\26\3\0\22\26\1\177\5\26"+
    "\21\0\7\26\6\0\7\26\3\0\27\26\1\75\21\0"+
    "\7\26\6\0\7\26\3\0\1\26\1\200\26\26\21\0"+
    "\7\26\6\0\7\26\3\0\16\26\1\201\11\26\21\0"+
    "\7\26\6\0\7\26\3\0\20\26\1\202\7\26\21\0"+
    "\7\26\6\0\7\26\3\0\11\26\1\203\16\26\21\0"+
    "\7\26\6\0\7\26\3\0\27\26\1\204\21\0\7\26"+
    "\6\0\7\26\3\0\15\26\1\205\12\26\21\0\7\26"+
    "\6\0\7\26\3\0\16\26\1\116\11\26\21\0\7\26"+
    "\6\0\7\26\3\0\10\26\1\125\1\206\16\26\21\0"+
    "\7\26\6\0\7\26\3\0\20\26\1\207\7\26\21\0"+
    "\7\26\6\0\7\26\3\0\11\26\1\210\16\26\21\0"+
    "\7\211\6\0\4\211\7\0\6\211\42\0\7\26\6\0"+
    "\5\26\1\212\1\26\3\0\30\26\21\0\7\26\6\0"+
    "\7\26\3\0\22\26\1\213\5\26\21\0\7\26\6\0"+
    "\7\26\3\0\22\26\1\214\5\26\21\0\7\26\6\0"+
    "\7\26\3\0\14\26\1\215\13\26\21\0\7\26\6\0"+
    "\7\26\3\0\3\26\1\216\24\26\21\0\7\26\6\0"+
    "\7\26\3\0\1\26\1\217\26\26\21\0\7\26\6\0"+
    "\7\26\3\0\13\26\1\220\14\26\21\0\7\26\6\0"+
    "\7\26\3\0\1\26\1\221\26\26\21\0\7\26\6\0"+
    "\7\26\3\0\5\26\1\163\22\26\21\0\7\26\6\0"+
    "\7\26\3\0\5\26\1\222\22\26\21\0\7\26\6\0"+
    "\7\26\3\0\3\26\1\223\24\26\21\0\7\26\6\0"+
    "\7\26\3\0\20\26\1\224\7\26\21\0\7\26\6\0"+
    "\7\26\3\0\21\26\1\225\6\26\21\0\7\26\6\0"+
    "\7\26\3\0\11\26\1\226\16\26\21\0\7\26\6\0"+
    "\7\26\3\0\1\26\1\227\26\26\21\0\7\26\6\0"+
    "\7\26\3\0\2\26\1\230\25\26\21\0\7\26\6\0"+
    "\7\26\3\0\6\26\1\231\21\26\21\0\7\26\6\0"+
    "\7\26\3\0\5\26\1\232\22\26\21\0\7\26\6\0"+
    "\7\26\3\0\14\26\1\233\13\26\21\0\7\26\6\0"+
    "\7\26\3\0\1\26\1\234\26\26\21\0\7\26\6\0"+
    "\7\26\3\0\1\26\1\205\26\26\21\0\7\26\6\0"+
    "\7\26\3\0\5\26\1\235\22\26\21\0\7\26\6\0"+
    "\7\26\3\0\3\26\1\236\24\26\21\0\7\26\6\0"+
    "\7\26\3\0\5\26\1\237\22\26\21\0\7\26\6\0"+
    "\7\26\3\0\7\26\1\163\20\26\21\0\7\26\6\0"+
    "\7\26\3\0\5\26\1\240\22\26\21\0\7\26\6\0"+
    "\7\26\3\0\15\26\1\241\6\26\1\242\3\26\21\0"+
    "\7\26\6\0\7\26\3\0\22\26\1\243\5\26\21\0"+
    "\7\26\6\0\7\26\3\0\13\26\1\244\14\26\21\0"+
    "\7\26\6\0\7\26\3\0\23\26\1\245\4\26\21\0"+
    "\7\26\6\0\7\26\3\0\15\26\1\246\12\26\21\0"+
    "\7\26\6\0\7\26\3\0\20\26\1\205\7\26\21\0"+
    "\7\26\6\0\7\26\3\0\11\26\1\247\11\26\1\250"+
    "\4\26\21\0\7\26\6\0\7\26\3\0\22\26\1\251"+
    "\5\26\21\0\7\26\6\0\7\26\3\0\22\26\1\163"+
    "\5\26\21\0\7\26\6\0\7\26\3\0\15\26\1\252"+
    "\12\26\21\0\7\26\6\0\7\26\3\0\13\26\1\253"+
    "\14\26\21\0\7\254\6\0\4\254\7\0\6\254\42\0"+
    "\7\26\6\0\7\26\3\0\15\26\1\255\12\26\21\0"+
    "\7\26\6\0\5\26\1\131\1\26\3\0\30\26\21\0"+
    "\7\26\6\0\7\26\3\0\17\26\1\256\10\26\21\0"+
    "\7\26\6\0\7\26\3\0\11\26\1\257\16\26\21\0"+
    "\7\26\6\0\7\26\3\0\7\26\1\260\20\26\21\0"+
    "\7\26\6\0\7\26\3\0\12\26\1\261\15\26\21\0"+
    "\7\26\6\0\7\26\3\0\10\26\1\262\17\26\21\0"+
    "\7\26\6\0\7\26\3\0\21\26\1\263\6\26\21\0"+
    "\7\26\6\0\7\26\3\0\14\26\1\264\13\26\21\0"+
    "\7\26\6\0\7\26\3\0\23\26\1\265\4\26\21\0"+
    "\7\26\6\0\7\26\3\0\13\26\1\147\14\26\21\0"+
    "\7\26\6\0\7\26\3\0\13\26\1\266\14\26\21\0"+
    "\7\26\6\0\7\26\3\0\1\26\1\267\26\26\21\0"+
    "\7\26\6\0\7\26\3\0\22\26\1\270\5\26\21\0"+
    "\7\26\6\0\7\26\3\0\20\26\1\271\7\26\21\0"+
    "\7\26\6\0\7\26\3\0\21\26\1\272\6\26\21\0"+
    "\7\26\6\0\7\26\3\0\22\26\1\273\5\26\21\0"+
    "\7\26\6\0\7\26\3\0\1\26\1\274\26\26\21\0"+
    "\7\26\6\0\7\26\3\0\5\26\1\275\22\26\21\0"+
    "\7\26\6\0\7\26\3\0\11\26\1\276\16\26\21\0"+
    "\7\26\6\0\7\26\3\0\20\26\1\277\7\26\21\0"+
    "\7\26\6\0\7\26\3\0\11\26\1\300\16\26\21\0"+
    "\7\26\6\0\7\26\3\0\15\26\1\301\12\26\21\0"+
    "\7\26\6\0\7\26\3\0\3\26\1\302\24\26\21\0"+
    "\7\26\6\0\7\26\3\0\3\26\1\303\24\26\21\0"+
    "\7\26\6\0\7\26\3\0\7\26\1\304\20\26\21\0"+
    "\7\26\6\0\7\26\3\0\5\26\1\305\22\26\21\0"+
    "\7\306\6\0\4\306\7\0\6\306\42\0\7\26\6\0"+
    "\7\26\3\0\22\26\1\307\5\26\21\0\7\26\6\0"+
    "\7\26\3\0\13\26\1\310\14\26\21\0\7\26\6\0"+
    "\7\26\3\0\14\26\1\311\13\26\21\0\7\26\6\0"+
    "\7\26\3\0\11\26\1\312\16\26\21\0\7\26\6\0"+
    "\7\26\3\0\1\26\1\313\26\26\21\0\7\26\6\0"+
    "\7\26\3\0\13\26\1\314\14\26\21\0\7\26\6\0"+
    "\7\26\3\0\13\26\1\315\14\26\21\0\7\26\6\0"+
    "\7\26\3\0\3\26\1\316\24\26\21\0\7\26\6\0"+
    "\7\26\3\0\11\26\1\317\16\26\21\0\7\26\6\0"+
    "\7\26\3\0\6\26\1\320\6\26\1\321\12\26\21\0"+
    "\7\26\6\0\7\26\3\0\17\26\1\322\10\26\21\0"+
    "\7\26\6\0\7\26\3\0\16\26\1\323\11\26\21\0"+
    "\7\26\6\0\7\26\3\0\22\26\1\324\5\26\21\0"+
    "\7\26\6\0\7\26\3\0\3\26\1\325\24\26\21\0"+
    "\7\26\6\0\7\26\3\0\3\26\1\326\24\26\21\0"+
    "\7\26\6\0\7\26\3\0\15\26\1\327\12\26\21\0"+
    "\7\26\6\0\7\26\3\0\7\26\1\330\20\26\21\0"+
    "\7\26\6\0\7\26\3\0\22\26\1\331\5\26\21\0"+
    "\7\26\6\0\7\26\3\0\10\26\1\332\17\26\21\0"+
    "\7\56\6\0\4\56\7\0\6\56\42\0\7\26\6\0"+
    "\7\26\3\0\5\26\1\333\22\26\21\0\7\26\6\0"+
    "\7\26\3\0\5\26\1\334\22\26\21\0\7\26\6\0"+
    "\7\26\3\0\1\26\1\335\26\26\21\0\7\26\6\0"+
    "\7\26\3\0\15\26\1\336\12\26\21\0\7\26\6\0"+
    "\7\26\3\0\13\26\1\163\14\26\21\0\7\26\6\0"+
    "\7\26\3\0\22\26\1\337\5\26\21\0\7\26\6\0"+
    "\7\26\3\0\27\26\1\340\21\0\7\26\6\0\7\26"+
    "\3\0\10\26\1\341\17\26\21\0\7\26\6\0\7\26"+
    "\3\0\16\26\1\342\11\26\21\0\7\26\6\0\7\26"+
    "\3\0\1\26\1\343\26\26\21\0\7\26\6\0\7\26"+
    "\3\0\1\26\1\344\26\26\21\0\7\26\6\0\7\26"+
    "\3\0\1\26\1\345\26\26\21\0\7\26\6\0\7\26"+
    "\3\0\5\26\1\326\22\26\21\0\7\26\6\0\7\26"+
    "\3\0\22\26\1\346\5\26\21\0\7\26\6\0\7\26"+
    "\3\0\7\26\1\347\20\26\21\0\7\26\6\0\7\26"+
    "\3\0\26\26\1\163\1\26\21\0\7\26\6\0\7\26"+
    "\3\0\13\26\1\350\14\26\21\0\7\26\6\0\7\26"+
    "\3\0\1\26\1\351\26\26\21\0\7\26\6\0\7\26"+
    "\3\0\15\26\1\352\12\26\21\0\7\26\6\0\7\26"+
    "\3\0\3\26\1\353\24\26\21\0\7\26\6\0\7\26"+
    "\3\0\13\26\1\326\14\26\21\0\7\26\6\0\7\26"+
    "\3\0\3\26\1\354\24\26\21\0\7\26\6\0\7\26"+
    "\3\0\5\26\1\355\22\26\21\0\7\26\6\0\7\26"+
    "\3\0\5\26\1\356\22\26\21\0\1\26\1\357\1\26"+
    "\1\112\1\26\1\105\1\26\6\0\7\26\3\0\30\26"+
    "\21\0\7\26\6\0\7\26\3\0\20\26\1\360\7\26"+
    "\21\0\7\26\6\0\7\26\3\0\5\26\1\361\22\26"+
    "\21\0\7\26\6\0\7\26\3\0\5\26\1\362\22\26"+
    "\21\0\7\26\6\0\7\26\3\0\4\26\1\326\23\26"+
    "\21\0\7\26\6\0\7\26\3\0\20\26\1\163\7\26"+
    "\21\0\2\26\1\363\4\26\6\0\7\26\3\0\30\26"+
    "\21\0\7\26\6\0\7\26\3\0\27\26\1\163\21\0"+
    "\6\26\1\163\6\0\7\26\3\0\30\26\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[12224];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\2\11\1\1\5\11\1\1\2\11"+
    "\3\1\1\11\3\1\2\11\20\1\1\11\1\1\1\11"+
    "\1\0\1\11\1\0\4\11\51\1\1\0\52\1\1\0"+
    "\42\1\1\0\31\1\1\0\55\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private java_cup.runtime.Symbol symbol(int type) {
        return new java_cup.runtime.Symbol(type, yyline, yycolumn);
    }
    private java_cup.runtime.Symbol symbol(int type, Object value) {
        return new java_cup.runtime.Symbol(type, yyline, yycolumn, value);
        }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(sym.ERRORL, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 59: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 60: break;
          case 3:
            { return new Symbol(sym.PARENTESISABIERTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 61: break;
          case 4:
            { return new Symbol(sym.PARENTESISCERRADO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 62: break;
          case 5:
            { return new Symbol(sym.MULTI, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 63: break;
          case 6:
            { return new Symbol(sym.MAS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 64: break;
          case 7:
            { return new Symbol(sym.COMA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 65: break;
          case 8:
            { return new Symbol(sym.MENOS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 66: break;
          case 9:
            { return new Symbol(sym.PUNTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 67: break;
          case 10:
            { return new Symbol(sym.DIV, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 68: break;
          case 11:
            { return new Symbol(sym.NUMERICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 69: break;
          case 12:
            { return new Symbol(sym.PUNTODOBLE, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 70: break;
          case 13:
            { return new Symbol(sym.PUNTOCOMA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 71: break;
          case 14:
            { return new Symbol(sym.OPERADORRELACIONAL, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 72: break;
          case 15:
            { return new Symbol(sym.OPERADORASIGNAMIENTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 73: break;
          case 16:
            { return new Symbol(sym.OPERADORTERNARIO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 74: break;
          case 17:
            { return new Symbol(sym.ID, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 75: break;
          case 18:
            { return new Symbol(sym.CORCHETEABIERTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 76: break;
          case 19:
            { return new Symbol(sym.CORCHETECERRADO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 77: break;
          case 20:
            { return new Symbol(sym.LLAVEABIERTA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 78: break;
          case 21:
            { return new Symbol(sym.LLAVECERRADA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 79: break;
          case 22:
            { return new Symbol(sym.LITERAL, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 80: break;
          case 23:
            { return new Symbol(sym.OPERADORCONLOGICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 81: break;
          case 24:
            { return new Symbol(sym.OPERADORRESULTADO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 82: break;
          case 25:
            { return new Symbol(sym.OPERADORDESPLAZAMIENTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 83: break;
          case 26:
            { return new Symbol(sym.SI, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 84: break;
          case 27:
            { return new Symbol(sym.PARAMETROENTRADA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 85: break;
          case 28:
            { return new Symbol(sym.HACER, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 86: break;
          case 29:
            { return new Symbol(sym.TIPONUMERICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 87: break;
          case 30:
            { return new Symbol(sym.POR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 88: break;
          case 31:
            { return new Symbol(sym.DEC, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 89: break;
          case 32:
            { return new Symbol(sym.INTENTAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 90: break;
          case 33:
            { return new Symbol(sym.TIPOINFERIDO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 91: break;
          case 34:
            { return new Symbol(sym.LISTA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 92: break;
          case 35:
            { return new Symbol(sym.TIPOLOGICO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 93: break;
          case 36:
            { return new Symbol(sym.CASO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 94: break;
          case 37:
            { return new Symbol(sym.TIPOCARACTER, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 95: break;
          case 38:
            { return new Symbol(sym.SINOHACER, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 96: break;
          case 39:
            { return new Symbol(sym.SINO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 97: break;
          case 40:
            { return new Symbol(sym.AGRUPACIONENUMERATOR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 98: break;
          case 41:
            { return new Symbol(sym.PARAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 99: break;
          case 42:
            { return new Symbol(sym.ATRAPAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 100: break;
          case 43:
            { return new Symbol(sym.AGRUPACIONSECUNDARIA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 101: break;
          case 44:
            { return new Symbol(sym.ESCANEAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 102: break;
          case 45:
            { return new Symbol(sym.GESTIONRECURSOS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 103: break;
          case 46:
            { return new Symbol(sym.MIENTRAS, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 104: break;
          case 47:
            { return new Symbol(sym.IMPRIMIR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 105: break;
          case 48:
            { return new Symbol(sym.MODIFICADORACCESO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 106: break;
          case 49:
            { return new Symbol(sym.RETORNAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 107: break;
          case 50:
            { return new Symbol(sym.TIPOCADENA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 108: break;
          case 51:
            { return new Symbol(sym.AGRUPACIONESTRUCTURA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 109: break;
          case 52:
            { return new Symbol(sym.SELECTOR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 110: break;
          case 53:
            { return new Symbol(sym.DEFECTO, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 111: break;
          case 54:
            { return new Symbol(sym.TERMINAR, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 112: break;
          case 55:
            { return new Symbol(sym.PORCADA, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 113: break;
          case 56:
            { return new Symbol(sym.DECLARACIONFUNCION, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 114: break;
          case 57:
            { return new Symbol(sym.AGRUPACIONINTERFAZ, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 115: break;
          case 58:
            { return new Symbol(sym.AGRUPACIONPRINCIPAL, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 116: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
