
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERICO = 13;
  public static final int PUNTO = 15;
  public static final int OPERADORDESPLAZAMIENTO = 8;
  public static final int PORCADA = 5;
  public static final int TIPONUMERICO = 11;
  public static final int OPERADORASIGNAMIENTO = 9;
  public static final int CORCHETECERRADO = 23;
  public static final int ERROR = 24;
  public static final int PUNTODOBLE = 17;
  public static final int OPERADORARITMETICO = 6;
  public static final int LITERAL = 14;
  public static final int OPERADORRELACIONAL = 7;
  public static final int PARENTESISCERRADO = 21;
  public static final int ID = 12;
  public static final int POR = 2;
  public static final int PARENTESISABIERTO = 20;
  public static final int EOF = 0;
  public static final int LLAVEABIERTA = 18;
  public static final int error = 1;
  public static final int PARAMETROENTRADA = 10;
  public static final int PUNTOCOMA = 16;
  public static final int CORCHETEABIERTO = 22;
  public static final int MIENTRAS = 4;
  public static final int HACER = 3;
  public static final int LLAVECERRADA = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "POR",
  "HACER",
  "MIENTRAS",
  "PORCADA",
  "OPERADORARITMETICO",
  "OPERADORRELACIONAL",
  "OPERADORDESPLAZAMIENTO",
  "OPERADORASIGNAMIENTO",
  "PARAMETROENTRADA",
  "TIPONUMERICO",
  "ID",
  "NUMERICO",
  "LITERAL",
  "PUNTO",
  "PUNTOCOMA",
  "PUNTODOBLE",
  "LLAVEABIERTA",
  "LLAVECERRADA",
  "PARENTESISABIERTO",
  "PARENTESISCERRADO",
  "CORCHETEABIERTO",
  "CORCHETECERRADO",
  "ERROR"
  };
}

